### ISSUE TITLE
More compilation problems

### ISSUE THREAD

**Issue by ib00** [GPUOpen-LibrariesAndSDKs/HIPRT#8]
Compilation (on Linux and for CUDA) is still not without problems. I am following instructions in README.

1.  If compiling with CUDA (ie, without HIP), you immediately get the following error:
HIPRT_API_VERSION: 02003_0x7df94af
sh: line 1: hipcc: command not found
HIP_VERSION_STR: HIP_SDK_NOT_FOUND
HIPRT_API_VERSION: 02003_0x7df94af
sh: line 1: hipcc: command not found
HIP_VERSION_STR: HIP_SDK_NOT_FOUND
/bin/sh: line 1: hipcc: command not found
Bitcodes Compile Error: executing command: hipcc --version
/bin/sh: line 1: hipcc: command not found

This is however harmless as compilation continues.

2. Another harmless error:

 >> BakeKernel Executed
mkdir: cannot create directory ‘hiprt/cache’: File exists

3. If you use "--precompile" flag the above with hipcc crashes kernel compilation:

Traceback (most recent call last):
  File "/tmp/HIPRT/scripts/bitcodes/compile.py", line 164, in <module>
    compileAmd()
  File "/tmp/HIPRT/scripts/bitcodes/compile.py", line 83, in compileAmd
    result = subprocess.check_output(cmd, shell=True)

4. After modifying "compile.py" script, the kernel compilation continues, but you get a bunch of errors like:

compiling hiprt02003_nv_lib.fatbin...
../../hiprt/hiprt_common.h(127): error: identifier "uint8_t" is undefined
  static_assert( ( sizeof( uint8_t ) == 1 ), "" );
                           ^

This can be fixed by including:

#include <stdint.h>

in "hiprt/hiprt_common.h"

5. Compile warning:

../../hiprt/impl/PlocBuilderKernels.h(142): warning #186-D: pointless comparison of unsigned integer with zero
   if ( index >= 0 && index < numberOfClusters )
              ^

6. Kernel compilation eventually succeeds, but some more errors:

Compilation SUCCEEDED.
compiling oro_compiled_kernels.fatbin...
Compilation SUCCEEDED.
export built programs ...
cp: target '../../dist/bin/Debug/': No such file or directory
cp: target '../../dist/bin/Release/': No such file or directory

7. After trying to run the unit tests:

../dist/bin/Release/unittest64 -p

tests run, but it takes a long time for tests to start. Are the kernels being recompiled?

**Comment by meistdan** [comment]
Thank you for reporting these issues. We will address them. Regarding the longer run times, with `--bitcode --precompile` options only the user code should be compiled and linked with the HIPRT trace kernels in runtime. Without `--bitcode --precompile`, all kernels are compiled for the first time and cached for the next runs.
